//CONSTANTS
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR'
export const SET_CONFIGURATION = 'SET_CONFIGURATION'
export const SET_ARTICLES = 'SET_ARTICLES'
export const SET_CURRENT_SECTION = 'SET_CURRENT_SECTION'
export const SET_POLITICS = 'SET_POLITICS'
